### ISSUE TITLE
Compilation error on GCC 6

### ISSUE THREAD

**Issue by One1One1One** [Bionus/imgbrd-grabber#1375]
**Bug description**

The compilation of the dev branch doesn't work anymore. It worked about one month ago. Look at the screenshot for more info on the error. It seems to me like the requirements for this project have changed. I tested it on two systems, one I set up one year ago and one that I just set up recently. Both have all updates installed.

**Steps to reproduce**

1. download f7968368 from the development branch
2. open build.sh and replace make -j8 with make to locate the error easier
3. execute build.sh
4. wait for the following error to show up
![error](https://user-images.githubusercontent.com/1807632/43994638-ad210a86-9da0-11e8-9225-b6f599a817e9.png)

**Expected behavior**

compilatrion success

**System information**

- OS: Raspbian (stretch)
- Grabber version: dev source (f7968368)
- g++: 6.3.0
- QMake: 3.0
- Qt: 5.7.1

**Comment by One1One1One** [comment]
I did some experiments on my own. I installed libqt5sql5-mysql, libqt5sql5-odbc and libqt5sql5-psql on both of my machines and here are the results:

Machine 1:
```
g++ --version
g++ (Raspbian 4.8.5-4) 4.8.5
```
Compilation successful

Machine 2:
```
g++ --version
g++ (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516
```
Compilation failed

Seems like it works with g++ 4.8, but not with g++ 6.3

**Comment by One1One1One** [comment]
That was the solution. Compilation fails with g++ 6.3, but works with g++4.8. Maybe it should be noted in the compilation guide. I'm not sure if it's a Raspbian-only thing though.

Can be closed.

**Comment by Bionus** [comment]
Not sure I'm willing to close this yet.
IMO there's no reason the program shouldn't build on newer GCC versions.

The CI runs on 4.8.4 currently, I'll see if there's a way to add an image with a more recent version, then fix this building issue (from what I see, simply including `functional` explicitly should be enough here). 👌

**Comment by One1One1One** [comment]
> -- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

![screenshot](https://user-images.githubusercontent.com/1807632/44007148-cd7f6e80-9e90-11e8-9804-4384df106486.png)

g++ and gcc 4.8.5 still works like a charm. As for 6.3.0 nothing has changed.

**Comment by Bionus** [comment]
Reproduced on Travis:
https://travis-ci.org/Bionus/imgbrd-grabber/jobs/415413698

**Comment by One1One1One** [comment]
FIXXED. Thank you.
