### ISSUE TITLE
imgbrd-grabber unable to compiler after Arch Linux's glibc updating to 2.35. Old Catch2?

### ISSUE THREAD

**Issue by HurricanePootis** [Bionus/imgbrd-grabber#2609]
**Bug description**

The build process fails to compile, specifically code involving Catch2. From my limited knowledge, seems like Catch2 isn't working with glibc 2.35.

The git repo is currently set to take an older version of Catch 2, git commit `f0dc4d9be078d21ccabcb0798f03c332a153f84f`.  Maybe we need to use a new Catch2 commit?

I am using [this PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=imgbrd-grabber)

**Steps to reproduce**

1. Download PKGBUILD on Arch linux with latest updates
2.  `makepkg -s`
3. Get build error
```
[ 47%] Building CXX object tests/CMakeFiles/tests.dir/src/integration/e621-test.cpp.o
In file included from /usr/include/signal.h:328,
                 from /home/hurricane/imgbrd-grabber/src/imgbrd-grabber/src/tests/src/vendor/catch/single_include/catch2/catch.hpp:8039,
                 from /home/hurricane/imgbrd-grabber/src/imgbrd-grabber/src/tests/src/common/main.cpp:9:
/home/hurricane/imgbrd-grabber/src/imgbrd-grabber/src/tests/src/vendor/catch/single_include/catch2/catch.hpp:10827:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10827 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /home/hurricane/imgbrd-grabber/src/imgbrd-grabber/src/tests/src/vendor/catch/single_include/catch2/catch.hpp:8039,
                 from /home/hurricane/imgbrd-grabber/src/imgbrd-grabber/src/tests/src/common/main.cpp:9:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from /home/hurricane/imgbrd-grabber/src/imgbrd-grabber/src/tests/src/common/main.cpp:9:
/home/hurricane/imgbrd-grabber/src/imgbrd-grabber/src/tests/src/vendor/catch/single_include/catch2/catch.hpp:10886:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10886 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~
/home/hurricane/imgbrd-grabber/src/imgbrd-grabber/src/gui/src/batch/batch-window.cpp: In constructor ‘BatchWindow::BatchWindow(QSettings*, QWidget*)’:
/home/hurricane/imgbrd-grabber/src/imgbrd-grabber/src/gui/src/batch/batch-window.cpp:34:22: warning: ‘void QTime::start()’ is deprecated: Use QElapsedTimer instead [-Wdeprecated-declarations]
   34 |         m_time->start();
      |         ~~~~~~~~~~~~~^~
```

**Expected behavior**

For the program to build correctly.

**System information**

- OS: Arch Linux
- Grabber version: 7.7.1

**Additional context**

glibc updated, and we're using an old version of Catch2

**Comment by Bionus** [comment]
Seems like it corresponds to catchorg/Catch2#2178 which was solved recently.
Likely need to bump Catch2.

**Comment by HurricanePootis** [comment]
Cool. Would it be hard to bump catch?
